import Head from 'next/head'
import Layout from '../components/Layout';
import { InferGetServerSidePropsType } from 'next';
import { getAllPosts } from '../lib/db';

export default function HomeSSR(props: InferGetServerSidePropsType<typeof getServerSideProps>) {
    return (
        <Layout>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <h1>Welcome to Homepage</h1>
            <h2>Latest POSTS</h2>
            <h3>TIME:{ Date.now() }</h3>
            <ul>{ props.posts.map(e => {
                return <li key={ e.title }>{ e.title }</li>
            }) }</ul>
        </Layout>
    )
}


export const getServerSideProps = async () => {
    const posts = await getAllPosts()
    return { props: { posts } }
}