import Head from 'next/head'
import Layout from '../components/Layout';
import { useEffect, useState } from 'react';
import { Post } from '../Types/Types';

export default function HomeCSR() {
    const [posts, setPosts] = useState<Post[]>()
    useEffect(() => {
        const fetchPosts = async () => {
            const res = await fetch(`${ process.env.NEXT_PUBLIC_API_URL }/api/posts`)
            const posts: Post[] = await res.json()
            setPosts(posts)
        }
        fetchPosts();
    }, [])
    return (
        <Layout>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <h1>Welcome to Homepage</h1>
            <h2>Latest POSTS</h2>
            <h3>TIME:{ Date.now() }</h3>
            { !posts
                ? (<div>Loader</div>
                ) : (
                    <ul>{ posts.map(e => {
                        return <li key={ e.title }>{ e.title }</li>
                    }) }
                    </ul>) }

        </Layout>
    )
}


