import Head from 'next/head'
import Link, { InferGetStaticPropsType } from 'next'
import Layout from '../components/Layout';
import { getAllPosts } from '../lib/db';

export default function Home(props: InferGetStaticPropsType<typeof getStaticProps>) {
    return (
        <Layout>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <h1>Welcome to Homepage</h1>
            <h2>Latest POSTS</h2>
            <h3>TIME:{ Date.now() }</h3>
            <ul>{ props.posts.map(post => {
                return (<li key={ post.id }>
                    <Link href="/post/[id]" as={ `/post/${ post.id }` }>
                        <a>{ post.title }</a>
                    </Link>
                </li>)
            }) }</ul>
        </Layout>
    )
}


export const getStaticProps = async () => {
    const posts = await getAllPosts()
    return { props: { posts } }
}